name: Fetch YouBike Data + Upload to Google Drive

on:
  schedule:
    - cron: "* * * * *"  # 每分鐘執行一次
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run YouBike fetch script
      run: python YoubikeMain.py  # <-- 改成你的實際檔名

    - name: Install rclone
      run: |
        curl https://rclone.org/install.sh | sudo bash

    - name: Configure rclone
      run: |
        mkdir -p ~/.config/rclone
        echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}

    - name: Upload to Google Drive
      run: |
        today=$(date +%F)
        rclone copy data gdrive:YouBikeData/$today/
