name: YouBike Fetch

on:
  schedule:
    - cron: "*/1 * * * *"  # 每分鐘執行一次
  workflow_dispatch:       # 也允許手動觸發

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run YouBike fetch script
        run: |
          python youbike_fetch.py

      - name: Commit DB changes
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add youbike_data.db
          git commit -m "Update DB at $(date)" || echo "No changes to commit"
          git push origin main

